Update deploy-cloudflare.yml

diff --git a/.github/workflows/deploy-cloudflare.yml b/.github/workflows/deploy-cloudflare.yml
--- a/.github/workflows/deploy-cloudflare.yml
+++ b/.github/workflows/deploy-cloudflare.yml
@@ -231,28 +231,28 @@ jobs:
           echo "worker_url=$WORKER_URL" >> $GITHUB_OUTPUT
           echo "✅ Setup completed."
 
-      - name: ♻️ 初始化数据库 / Initialize database
-        run: |
-          echo "🛠️ Starting database initialization..."
-          sleep 15
+      # - name: ♻️ 初始化数据库 / Initialize database
+      #   run: |
+      #     echo "🛠️ Starting database initialization..."
+      #     sleep 15
           
-          WORKER_URL="${CUSTOM_DOMAIN:+https://$CUSTOM_DOMAIN}"
-          WORKER_URL="${WORKER_URL:-${{ steps.deploy.outputs.worker_url }}}"
+      #     WORKER_URL="${CUSTOM_DOMAIN:+https://$CUSTOM_DOMAIN}"
+      #     WORKER_URL="${WORKER_URL:-${{ steps.deploy.outputs.worker_url }}}"
           
-          if [ -z "$WORKER_URL" ]; then
-            echo "❌ Preview URL not available. Please set CUSTOM_DOMAIN."
-            exit 1
-          fi
+      #     if [ -z "$WORKER_URL" ]; then
+      #       echo "❌ Preview URL not available. Please set CUSTOM_DOMAIN."
+      #       exit 1
+      #     fi
           
-          HTTP_CODE=$(curl -sL -w "%{http_code}" -o response.txt "$WORKER_URL/api/init/${JWT_SECRET}")
-          RESPONSE_BODY=$(cat response.txt)
+      #     HTTP_CODE=$(curl -sL -w "%{http_code}" -o response.txt "$WORKER_URL/api/init/${JWT_SECRET}")
+      #     RESPONSE_BODY=$(cat response.txt)
 
-          if [ "$RESPONSE_BODY" = "success" ]; then
-            echo "✅ Setup completed."
-          else
-            echo "❌ Failed. HTTP: $HTTP_CODE, Response: $RESPONSE_BODY"
-            exit 1
-          fi
+      #     if [ "$RESPONSE_BODY" = "success" ]; then
+      #       echo "✅ Setup completed."
+      #     else
+      #       echo "❌ Failed. HTTP: $HTTP_CODE, Response: $RESPONSE_BODY"
+      #       exit 1
+      #     fi
 
       - name: 🗑️ 删除运行记录 / Delete workflow runs
         uses: GitRML/delete-workflow-runs@main
